// Generated by FlutterFire CLI. Replace with output of:
//   flutterfire configure
//
// Steps:
//   1. Create project at https://console.firebase.google.com
//   2. Install CLI: dart pub global activate flutterfire_cli
//   3. Run: flutterfire configure
//   4. Commit the generated file (it contains no secrets — keys are restricted by package name)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure',
        );
    }
  }

  // Replace all values below by running: flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: 'REPLACE_WITH_REAL_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_PROJECT_ID.appspot.com',
  );
}
